apiVersion: v2
name: rustdb
description: A Helm chart for RustDB
type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - database
  - rust
  - sql

maintainers:
  - name: RustDB Contributors
    email: maintainers@rustdb.dev

home: https://github.com/zishaan1911/RustDB
sources:
  - https://github.com/zishaan1911/RustDB
