# Temporary, no functionality at the moment
# Just to avoid errors when commiting and the yml is empty
name: No-op Security Workflow
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: No-op step
        run: echo "noop"

